### PR TITLE
README.md

### PR DESCRIPTION
**Pull request by Temp0-Sys**
Added tutorial for MacOS users using Apple's Game Porting Toolkit

### CODE REVIEW

**Comment by blueskythlikesclouds** [comment]
Can you fix the punctations and utilize `this type of marking` to put focus on important parts like I did in the original README? Thanks.

**Comment by Temp0-Sys** [comment]
Hope it's better now

**Comment by nastys** [comment]
``WINEDLLOVERRIDES='dinput8.dll=n,b'`` works on macOS, too, except you need to prepend it to ``gameportingtoolkit`` or ``gameportingtoolkit-noesync`` (which seems to be smoother than the main script with Esync enabled by default for me, although I haven't tested it very much).

Alternatively, you can run Steam with debug messages and Esync disabled for the best performance:
``WINEDLLOVERRIDES='dinput8.dll=n,b' WINEDEBUG=-all WINEESYNC=0 WINEPREFIX=~/your-wine-prefix `/usr/local/Homebrew/bin/brew --prefix game-porting-toolkit`/bin/wine64 'C:\Program Files (x86)/Steam/steam.exe' 2>/dev/null``

Of course, adding it in winecfg also works fine and I think it's more convenient anyway.
I personally use the override in winecfg and launch Steam with this command but without WINEDLLOVERRIDES.

**Comment by blueskythlikesclouds** [comment]
Looks good to me now. If you want to add the stuff Nas mentioned you can do so in another PR.

**Pull request merged**
